/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test
import org.testcontainers.containers.PostgreSQLContainer
import org.testcontainers.containers.output.Slf4jLogConsumer

class AppTest {
    @Test
    fun launchTestContainers() {
        val container = PostgreSQLContainer("postgres:14").apply {
            start()
        }
    }
}
