on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run Gradle
        run: ./gradlew build --no-daemon
        timeout-minutes: 10
      - name: Upload Gradle Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Gradle Reports
          path: |
            ./**/build/reports
            ./**/build/test-results
          if-no-files-found: ignore
